### ISSUE TITLE
Limiting results to two decimal places gives inaccurate results when working with small values.

### ISSUE THREAD

**Issue by codywatts** [anandanand84/technicalindicators#1]
In functions such as the SMA, the result is truncated to two decimal places before being returned to the caller. When working with numbers which are sufficiently small, this greatly impacts the accuracy/usefulness of the values which are returned.

**Comment by anandanand84** [comment]
Do you have an input and an expected value for this scenario?

**Comment by codywatts** [comment]
Example code:
```javascript
const technicalindicators = require('technicalindicators');

const values = [0.001, 0.003, 0.001, 0.003, 0.004, 0.002, 0.003, 0.003, 0.002];
const smaValues = technicalindicators.SMA.calculate({ period: 4, values: values });
console.log(smaValues);
```
Output:
```javascript
[ 0, 0, 0, 0, 0, 0 ]
```
Expected output:
```javascript
[ 0.002, 0.00275, 0.0025, 0.003, 0.003, 0.0025 ]
```

**Comment by chiu0602** [comment]
Would it be better to change `toFixed(x)` to `toPrecision(x)`?
