### ISSUE TITLE
GET http://model.bin/ net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by whittlem** [anandanand84/technicalindicators#101]
It has been a struggle to get even a basic implementation of technicalindicators working in React. At least I have something working now but still getting errors.

I created a React app using create-react-app. I then added all the packages from the technicalindicators package.json file.

My package.json looks like this:

{
  "name": "react-technicalindicators",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "@types/chai": "^3.0.0",
    "@types/mocha": "^2.0.0",
    "@types/node": "^6.0.31",
    "babel-cli": "^6.8.0",
    "babel-core": "^6.8.0",
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es2015-rollup": "^3.0.0",
    "babel-register": "^6.8.0",
    "babel-runtime": "^6.23.0",
    "chai": "^3.0.0",
    "draw-candlestick": "*",
    "gulp": "^3.9.1",
    "gulp-mocha": "^2.2.0",
    "gulp-util": "^3.0.8",
    "koa": "^2.2.0",
    "koa-static": "^3.0.0",
    "mocha": "^2.4.5",
    "monaco-editor": "^0.8.3",
    "rimraf": "^2.0.0",
    "rollup": "^0.41.6",
    "rollup-plugin-babel": "^2.7.1",
    "rollup-plugin-babel-minify": "^3.1.2",
    "rollup-plugin-commonjs": "^8.0.2",
    "rollup-plugin-node-resolve": "^3.0.0",
    "rollup-plugin-uglify": "^1.0.2",
    "rollup-watch": "^3.2.2",
    "ts-node": "^1.0.0",
    "tslint": "^4.0.0",
    "typescript": "^2.0.0",
    "graceful-fs": "^4.1.11",
    "minimatch": "^3.0.4",
    "pug": "^2.0.0-rc.4"
  },
  "dependencies": {
    "@types/node": "^6.0.96",
    "babel-polyfill": "^6.23.0",
    "babel-preset-env": "^1.6.1",
    "browser-js": "^1.10.1",
    "keras-js": "^1.0.2",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-scripts": "1.1.0",
    "technicalindicators": "^1.1.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

I needed to add this under <body> in my public/index.html:

    <script src="https://cdn.rawgit.com/transcranial/keras-js/master/dist/keras.min.js"></script>
    <script src="dist/browser.js"></script>

In my src/App.js I added this just above the class App.

var technicalindicators = require("technicalindicators")
var result = technicalindicators.window.sma({period : 5, values : [1,2,3,4,5,6,7,8,9], reversedInput : true});
console.log(result);

The good news is I actually get a result with this approach but still getting a stack of errors.

My browser console is showing this:

(5) [3, 4, 5, 6, 7]           App.js:7

GET http://model.bin/ net::ERR_NAME_NOT_RESOLVED           keras.min.js:1
Error: Network Error
    at t (keras.min.js:1)
    at XMLHttpRequest.t (keras.min.js:1)  

Uncaught (in promise) Error: [Model] Model configuration does not contain any layers.          keras.min.js:1
    at t (https://cdn.rawgit.com/transcranial/keras-js/master/dist/keras.min.js:1:414319)
    at t (https://cdn.rawgit.com/transcranial/keras-js/master/dist/keras.min.js:1:411416)
    at r (https://cdn.rawgit.com/transcranial/keras-js/master/dist/keras.min.js:1:448353)
    at Generator.i [as _invoke] (https://cdn.rawgit.com/transcranial/keras-js/master/dist/keras.min.js:1:449400)
    at Generator.t.(anonymous function) [as throw] (https://cdn.rawgit.com/transcranial/keras-js/master/dist/keras.min.js:1:448532)
    at i (https://cdn.rawgit.com/transcranial/keras-js/master/dist/keras.min.js:1:164739)
    at s (https://cdn.rawgit.com/transcranial/keras-js/master/dist/keras.min.js:1:164860)
    at <anonymous>

Any idea how to fix this?

**Comment by anandanand84** [comment]
When running in browser the file model.bin present in dist/model.bin in the respository should be accessible on your server at the location at /dist/model.bin. The model is trained using 400 count of values, so try to provide values close to 400 for a reliable prediction.

Check readme for more info.

**Comment by whittlem** [comment]
The file is currently located here:

$ find . -name "model.bin"
./node_modules/technicalindicators/dist/model.bin

Do you mean I should move it to ./dist? or ./public/dist?

Does the server need to write to the file or just read from it?

**Comment by anandanand84** [comment]
>Based on your response I would have thought it would be looking for the file at http://localhost:3000/dist/model.bin

yes you are right the it will be looking for file at that location, move the file from ./node_modules/technicalindicators/dist/model.bin to location which corresponds to your /dist/model.bin location in your server

**Comment by whittlem** [comment]
So I copied model.bin into ./public/dist. 

It is still giving this error in the browser console:
GET http://model.bin/ net::ERR_NAME_NOT_RESOLVED keras.min.js:1

To prove the file is actually in the place you requested I confirmed it with wget:

$ wget http://localhost:3000/dist/model.bin
--2018-02-08 09:09:09--  http://localhost:3000/dist/model.bin
Connecting to localhost (localhost)|127.0.0.1|:3000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1473628 (1.4M) [application/octet-stream]
Saving to: ‘model.bin’

model.bin           100%[===================>]   1.41M  --.-KB/s    in 0.002s  

2018-02-08 09:09:09 (677 MB/s) - ‘model.bin’ saved [1473628/1473628]

What makes me doubt that will work is it is looking for the file here:

http://model.bin/

As in the FQDN model.bin so something doesn't look right.

What else can I try?

**Comment by anandanand84** [comment]
I am not a webpack expert and I am really not sure how create-react-app works internally, here is an simple video that demonstrate the basic working.

https://youtu.be/-q9ITNjlsHE

The only reason I can think of is it messes up the environment so it uses the node path to load the model which you can see from the below code.

```
import { Indicator, IndicatorInput } from '../indicator/indicator';
import { getConfig } from '../config';
import { Model } from 'keras-js';
var isNodeEnvironment = false;
(function () {
    if (typeof (module) !== 'undefined' && module.exports) {
        isNodeEnvironment = true;
    }
})();
var modelPath = getConfig('MODEL_PATH') || '/dist/model.bin';
var model = new Model({
    filepath: isNodeEnvironment ? __dirname + '/model.bin' : modelPath,
    gpu: false,
    filesystem: isNodeEnvironment
});
```
I am open to making changes if you have any suggestions. Thanks

**Comment by whittlem** [comment]
To make this easier I created a git repo:
https://github.com/whittlem/react-technicalindicators

If you run the following:

* git clone https://github.com/whittlem/react-technicalindicators
* npm install
* npm run start

And open the browser console you'll see what I'm seeing.

**Comment by anandanand84** [comment]
I looked into the project. There is multiple issues here
1.  Technical indicators has full module support. Your app (in this case react-starter-app) should use technicalindicators main, module or jsnext:main key in package.json to load the required classes in case if it wants to build on its own. But it is looking for browser key which is a built version for browsers with all classes on window object.

2. There is an issue in keras-js where it loads https://github.com/transcranial/keras-js/blob/master/src/index.js#L1 babel-polyfill which conflicts with babel-polyfill injected.

**Comment by whittlem** [comment]
Thanks.

I created the React starter app just to give me a simple base to test this. I am not sure what you mean regarding your first point. What should the package.json look like? I thought I had included the main technicalindicators package?

  "dependencies": {
    "@types/node": "^6.0.96",
    "babel-polyfill": "^6.23.0",
    "keras-js": "^1.0.2",
    "babel-preset-env": "^1.6.1",
    "browser-js": "^1.10.1",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-scripts": "1.1.0",
    "technicalindicators": "^1.1.3"    <--    HERE
  },

On the second point what do you suggest as a fix?

**Comment by anandanand84** [comment]
I do not use webpack or react so I could not really help here. With whatever knowledge I have, For the first,  if you have a webpack project, you need to add in your webpack config. 
```
module.exports = {
  resolve: {
    mainFields: ["module", "main"]
  }
}
```

For the second point I do not have a control over the other library other than to create a issue, that is why I havent included Kerasjs along with the package, you should still be able to use the library without kerasjs, the only thing you will be missing is pattern detection.

**Comment by levithomason** [comment]
Putting the `mode.bin` at `/dist/model.bin` also does not solve it for me.  FWIW, the second error regarding the model not having any layers is also present in the Playground demo:

http://anandanand84.github.io/technicalindicators/

It also does not work.

**Comment by whittlem** [comment]
Do you have a version that doesn't have the pattern detection included? I have not been able to get your package to work with KerasJS.

**Comment by anandanand84** [comment]
try ```npm install --save-exact technicalindicators@1.0.19```

**Comment by anandanand84** [comment]
@levithomason The playground still loads the model from /dist/model.bin but due to some issue with github pages it is not found.

**Comment by levithomason** [comment]
Would you be open to help setting up Webpack and separate build targets for CommonJS modules, ES modules, and UMD modules?  Each of these have slightly different requirements.  

The goal would be to install only `technicalindicators` and use any of the module targets with no additional installation or configuration required.  The `model.bin` would fall outside this requirement or need some more thinking.

I am the author of [Semantic-UI-React](https://github.com/Semantic-Org/Semantic-UI-React) and we've also done this with our package.  It then allows users to use any build system (Webpack, Rollup, etc.) or no build system by loading the UMD module directly in a browser.  Note, a UMD build like this also does not require any additional Babel compilation.

So far, this library accomplishes the most of what I'm after.  [`tulind`](https://www.npmjs.com/package/tulind) is the next best thing, but it is Node.js only, not isomorphic.  I'd like to stick with an isomorphic package if I can.

Thoughts?

**Comment by anandanand84** [comment]
@levithomason I am not sure if you saw my other https://github.com/anandanand84/technicalindicators/issues/98#issuecomment-365410059 . Currently we have builds for node, es6 and es5 seperately the only problem is with babel-polyfill that was added with kerasjs. If you think that is not a problem with webpack and cannot be solved by rollup, I am open for change and ready for pull request.

**Comment by anandanand84** [comment]
keras js is included in technicalindicators@1.1.4 and should load model.bin from dist

**Comment by levithomason** [comment]
Got it.  I've commented on the keras=js issue as well.

**Comment by anandanand84** [comment]
I have added a hack to remove the polyfill, so it should work now with kerasjs in the latest version.

**Comment by whittlem** [comment]
Which version are you referring too?

I tried:
"technicalindicators": "^1.1.4"

And still getting:
Uncaught Error: only one instance of @babel/polyfill is allowed

**Comment by whittlem** [comment]
And my keras-js version is:
"keras-js": "^1.0.3",

**Comment by anandanand84** [comment]
can you try this repo and let me know?

https://github.com/anandanand84/react-technicalindicators

**Comment by lsiric** [comment]
Hi @anandanand84, does that repo work for you? it seems to have the same, `babel polyfill can be defined only once` error?
