### ISSUE TITLE
Error when install with Browser

### ISSUE THREAD

**Issue by seekerquoc** [anandanand84/technicalindicators#108]
Hello,
I like this project and i try with browser but its not working.
Can you help me?

![image](https://user-images.githubusercontent.com/5293252/36515490-3d3954f0-17ac-11e8-8d1c-b4f125b28e50.png)

Thanks

**Comment by anandanand84** [comment]
@seekerquoc When running in browser the file model.bin present in dist/model.bin in the respository should be accessible on your server at the location at /dist/model.bin. But if you are trying to detect just candlestick that error is not an issue.

**Comment by seekerquoc** [comment]
Thank you for your reply. I tried with server but it still not working

![image](https://user-images.githubusercontent.com/5293252/36521230-4c199edc-17c8-11e8-93fa-f2d2cfd30ebf.png)


Thanks

**Comment by anandanand84** [comment]
This is not an issue.
