### ISSUE TITLE
Cannot find module "."

### ISSUE THREAD

**Issue by shaosh** [anandanand84/technicalindicators#110]
Hi @anandanand84 ,

Thank you so much for developing this amazing set of tools, which I've been looking for for a while. 

When I use this package without webpack, everything is good. However when I pack my code with webpack, it starts complaining 

`return /*require.resolve*/(!(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
                                                                                                                                               ^
Error: Cannot find module "."`

when I tried to run my code. (webpack build did not give any error). 

It did not change anything after I added ts-loader or `mainFields: ["module", "main"]` into my webpack.config.

I am quite sure this error is caused by technicalindicators, since it runs well after I remove this package. 

Just wondering if you saw this kind of error before, and if you can give any help. 

Thanks,
shaosh

**Comment by anandanand84** [comment]
@shaosh I haven't encountered this error and the error doesn't say much. I can take a look if you create a minimal github project reproducing the error.

Thanks

**Comment by shaosh** [comment]
@anandanand84 Could you take a look at the error and code I pasted above? It seems to be related with the patterndetection.js.

**Comment by anandanand84** [comment]
@shaosh Is there a sample project which I can look into, its hard to debug without reproducing the issue.

**Comment by shaosh** [comment]
@anandanand84 
Sorry. Here is the repo: https://github.com/shaosh/macd-demo
My node version is 8.4.0.

**Comment by anandanand84** [comment]
@shaosh Thankyou I'll check

**Comment by shaosh** [comment]
The reason for this issue is webpack which is based on uglifyjs can't uglify uglifyjs. Similar issue was also referred here:
https://github.com/mishoo/UglifyJS2/issues/1847
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/226
https://github.com/webpack/webpack/issues/4786

But I haven't seen any solutions. 

After being blocked here by this issue for a month, I finally figured out a workaround after came across this issue https://github.com/webpack/webpack/issues/603

If anyone sees the same issue and your application happens to be a server-side project as I do, just don't webpack the node_modules.

```
var nodeExternals = require('webpack-node-externals');
...
module.exports = {
    ...
    target: 'node', // in order to ignore built-in modules like path, fs, etc. 
    externals: [nodeExternals()], // in order to ignore all modules in node_modules folder 
    ...
};
```

**Comment by anandanand84** [comment]
@shaosh does this mean we can close this issue?

**Comment by shaosh** [comment]
@anandanand84 Yeah, I'll do it.
