### ISSUE TITLE
Is it possible to achieve a Stochastic RSI from RSI+Stochastics

### ISSUE THREAD

**Issue by flesler** [anandanand84/technicalindicators#112]
RSI has one output value and Stochastics expects 3, possible?

**Comment by anandanand84** [comment]
@flesler It is possible and simple, I'll try to write it when I find free time. 

Thanks

**Comment by anandanand84** [comment]
here is another thread for the same
https://github.com/anandanand84/technicalindicators/issues/72

**Comment by flesler** [comment]
It's indeed a dup, will close
