### ISSUE TITLE
RSI test failed

### ISSUE THREAD

**Issue by ivoglent** [anandanand84/technicalindicators#114]
I've just rerun the testing code of RSI indicator : [https://runkit.com/anandaravindan/rsi](https://runkit.com/anandaravindan/rsi) but the test was failed (see attached image for more details)
<img width="1107" alt="screen shot 2018-03-13 at 8 54 05 pm" src="https://user-images.githubusercontent.com/4499973/37346544-28515cbc-2702-11e8-8756-3617acd4a0be.png">

Node version : v8.9.2
TechnicalIndicators version : 1.1.5

I don't know why. If you have time please take a look. Thanks!

**Comment by anandanand84** [comment]
@ivoglent Can you provide more details. I can see the the result length is higher than expected, but how much is your input size. Screenshot cannot help. Please provide the test in text.

**Comment by ivoglent** [comment]
Okay, thank for your quick reply. Here is the test code : 
`
import {expect} from 'chai';
import 'mocha';

describe('Test RSI', () => {
   it('Starting test RSI with technicalindicators', () => {
       let RSI = require('technicalindicators').RSI;

       let inputRSI = {
           values : [127.75,129.02,132.75,145.40,148.98,137.52,147.38,139.05,137.23,149.30,162.45,178.95,200.35,221.90,243.23,243.52,286.42,280.27,277.35,269.02,263.23,214.90],
           period : 14
       };
       let expectedResult = [
           86.41,86.43,89.65,86.50,84.96,80.54,77.56,58.06
       ];
       let result = RSI.calculate(inputRSI);
       expect(result).to.deep.equal(expectedResult);

   });
});
`
I just copied from provided link :  [https://runkit.com/anandaravindan/rsi](https://runkit.com/anandaravindan/rsi) . Hope that helpful

**Comment by anandanand84** [comment]
@ivoglent Let me check. Looks like I have commented the RSI test in the library for some reason. I'll check why

**Comment by anandanand84** [comment]
Fixed and enabled tests for RSI.
