### ISSUE TITLE
Missing in pattern BearishHarami and BullishHarami

### ISSUE THREAD

**Issue by tuanna45** [anandanand84/technicalindicators#115]
I've read the code of two patterns and I see you have a missing between them. The coding of BearishHarami belonged to Bullish Harami pattern and vice verse. The same for BullishHaramiCross and BearishHaramiCross,... Do we need to reverse our input before passing them into these patterns or another thing? Please help me to verify again. Thanks.

![image](https://user-images.githubusercontent.com/31426828/37553811-82a3fc68-2a01-11e8-9844-ff706aa9bc80.png)

**Comment by anandanand84** [comment]
Can you run npm run test. It will create test images for each candlestick pattern, let me know if it is what you are expecting.

![image](https://user-images.githubusercontent.com/5538452/37561278-ab3b3c2e-2a18-11e8-805c-800fa5256083.png)

A google image search shows conflicting patterns

![image](https://user-images.githubusercontent.com/5538452/37561287-ed8b53d4-2a18-11e8-9b92-b894757ff7bc.png)

I am open for changes if we reach consensus. I would really appreciate if you can do a pull request

**Comment by JMoli** [comment]
@anandanand84 I do not see any conflicting images?

**Comment by tuanna45** [comment]
Sorry for my late, I find the best definition of these patterns. As you can see below and pay attention to strong text:

> **What is a 'Bullish Harami'**

> A bullish harami is a candlestick chart pattern in which a large candlestick is followed by a smaller candlestick whose body is located within the vertical range of the larger body. **The _bullish harami_ is a downtrend or bearish candlestick (red) engulfing a small bullish candlestick (green), giving a sign of a reversal of the downward trend**. Since the bullish harami indicates the bearish trend may be reversing, it may be a good time to enter into a long position.

![image](https://user-images.githubusercontent.com/31426828/37822168-4d29ebcc-2eb8-11e8-8a4d-bacdc774c1dc.png)

=> So I think we should swap code between "BearishHarami and BearishHaramiCross" and "BullishHaramiCross and BearishHaramiCross". Because we don't change anything business of these patterns so you can help me do that.

Reference document:
1) Bullish Harami: https://www.investopedia.com/terms/b/bullishharami.asp
2) Harami Cross: https://www.investopedia.com/terms/h/haramicross.asp

**Comment by anandanand84** [comment]
@JMoli can you add the cross as well in the pull request, I'll merge it together
