### ISSUE TITLE
Include babel-plugin-transform-runtime as part of babel config?

### ISSUE THREAD

**Issue by ben-berman-iex** [anandanand84/technicalindicators#118]
Hello, when I tried to use your library, I was not able to as it conflicted with the https://www.npmjs.com/package/bluebird Bluebird package I use. Apparently your usage of babel-polyfill overwrites Promises at the global scope. 

After researching a bit, I came across this possible solution: https://babeljs.io/docs/plugins/transform-runtime/

From the documentation: _"Another purpose of this transformer is to create a sandboxed environment for your code. If you use babel-polyfill and the built-ins it provides such as Promise, Set and Map, those will pollute the global scope. While this might be ok for an app or a command line tool, it becomes a problem if your code is a library which you intend to publish for others to use or if you can’t exactly control the environment in which your code will run."_

It would be great if this was added to your build so we could use your package along with Bluebird and not have babel-polyfill set Promise on the global scope, thanks!

**Comment by anandanand84** [comment]
This library doesn't add babel-polyfill but include keras-js which adds babel-polyfill. This is related to https://github.com/transcranial/keras-js/issues/109
