### ISSUE TITLE
RSI

### ISSUE THREAD

**Issue by t-westwood** [anandanand84/technicalindicators#121]
Hi, when i run the rsi on node.js, the result is not the same as on binance, im currently inputting 250 candle.close's, should I have less values in the array or more maybe? 

Thanks!

**Comment by anandanand84** [comment]
It is exactly the same between https://cryptotrading-hub.com and binance. Cryptotradinghub uses this library. Can you show your data about your comparison?

![image](https://user-images.githubusercontent.com/5538452/37995599-a44ef0bc-31da-11e8-909f-8607be7a03b3.png)

**Comment by t-westwood** [comment]
hi cheers for the quick reply, my data is coming up as the same as cryptohub. but if you compare for example, the last 10 candles rsi on TRXBTC (5 min candle) for both binance and cryptotradinghub, binance last 10 RSIs are in the 30's crypto hub is in the 50-60s?

**Comment by anandanand84** [comment]
well, it is wrong in binance, see below chart comparing cryptotradinghub and tradingview.

![screen shot 2018-03-27 at 5 10 30 pm](https://user-images.githubusercontent.com/5538452/37997833-eff3402a-31e1-11e8-897e-73640abb3ec7.png)

**Comment by anandanand84** [comment]
My guess is binance id not usinh more precision that is why it doesn't not work correct on low decimal markets.

**Comment by t-westwood** [comment]
haha Fair dooze! Awesome job by the way, you have legit saved me sooo much time, I have been been trying to code these indicators from scratch, and im pretty crap at coding haha. 
thanks for the reply mate, my mind is now put to ease lol.

**Comment by anandanand84** [comment]
You are welcome. I'll close this issue.

**Comment by saru2020** [comment]
I've found that the RSI works when all the data are given at once meaning don't feed in only period+1 or limited data per se, just input the whole list of values and the RSI indicator precisely matches the values in TV, it just works beautifully.
