### ISSUE TITLE
How to Calculate Real-time 1-Minute RSI value ？

### ISSUE THREAD

**Issue by fc01** [anandanand84/technicalindicators#122]
nextValue  ??

I need  updateValue  function 

const v = updateValue(13.4)         //last minute close is 13.4    __    real time call

**Comment by JMoli** [comment]
You mean getResult? 
https://github.com/anandanand84/technicalindicators#getresult

**Comment by anandanand84** [comment]
@fc01 Here is an example of using nextvalue.

https://github.com/anandanand84/technicalindicators/blob/master/test/oscillators/RSI.js#L66

**Comment by fc01** [comment]
```js
let a = new x.SMA({
    period: 3,
    values: [3, 1, 2, 4, 6]
})
console.log(a.getResult())  //[ 2, 2.3333333333333335, 4 ]

//a.updateLastValue(9)  //return 5      //The latest price is real time updates 

let b = new x.SMA({
    period: 3,
    values: [3, 1, 2, 4, 9]
})
console.log(b.getResult())  //[ 2, 2.3333333333333335, 5 ]

```

**Comment by mortezae** [comment]
For people who reach this issue via search: this question is answered in #123
