### ISSUE TITLE
how to update last value ?

### ISSUE THREAD

**Issue by fc01** [anandanand84/technicalindicators#123]
```js
let a = new x.SMA({
    period: 3,
    values: [3, 1, 2, 4, 6]
})
console.log(a.getResult())  //[ 2, 2.3333333333333335, 4 ]

//a.updateLastValue(9)  //return 5      //The latest price is real time updates 

let b = new x.SMA({
    period: 3,
    values: [3, 1, 2, 4, 9]
})
console.log(b.getResult())  //[ 2, 2.3333333333333335, 5 ]
```

**Comment by anandanand84** [comment]
There is no update last value. There is only nextValue

**Comment by slidenerd** [comment]
I double @fc01 you get live data for say a 1 hour chart that updates every second, how are you supposed to get the latest rsi for that duration without recalculating everything

**Comment by anandanand84** [comment]
as said there is no update last values there is only nextValue which means you will be able to get the next value after the bar completes and not intermediate updates
