### ISSUE TITLE
Another uglify issue

### ISSUE THREAD

**Issue by andyperisho** [anandanand84/technicalindicators#130]
```
ERROR in bundle.js from UglifyJs
Unexpected token: punc (;) [./node_modules/technicalindicators/lib/volume/ForceIndex.js:43,0][bundle.js:133310,4]
```

Once I remove the extra `;` from this file, I get the error for another file.
I guess that the `lib` files are actually converted from typescript? What's the best way to mitigate this error?

Thx.

**Comment by anandanand84** [comment]
@andyperisho I would say it is an issue with whatever uglify library you are using. Since it is a valid javascript, they should handle the minification.

**Comment by andyperisho** [comment]
Which one are you using?

**Comment by anandanand84** [comment]
I am using https://github.com/babel/minify

**Comment by andyperisho** [comment]
Ok, thx.
