### ISSUE TITLE
Error: Uncaught SyntaxError: Invalid regular expression on loading index.html

### ISSUE THREAD

**Issue by KashyapCKotak** [anandanand84/technicalindicators#133]
**I downloaded this from npm as instructed and wrote this in index.html:
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.23.0/polyfill.min.js"></script>
<script src="technicalindicators/dist/browser.js"></script>
in browser and got this error in esprima.js:**

![image](https://user-images.githubusercontent.com/20476571/40464354-6526a16a-5f38-11e8-8501-64fc7cf7ecf1.png)

**I am new to node and have no idea whats going on. how can I solve this issue? Please help :)**

**Comment by anandanand84** [comment]
I am not sure can you show me an github example. This packages is not dependent on esprima.js or softmax.js

**Comment by KashyapCKotak** [comment]
Thanks for your prompt response :)
The above issue was resolved when I replaced<script src="technicalindicators/dist/browser.js"></script> with https://unpkg.com/technicalindicators@1.1.11/dist/browser.js. Not sure why it didn't work through packages downloaded from npm. I didn't perform the bower install step. Hope that was not a problem.

I wanted to know one more thing:
When I pass data to MACD (SMA), which has 61 data points, only 36 MACD data points are returned. Shouldn't it be 61 data points returned? or am I missing something?

The code I am using to test is what you provided at https://tonicdev.com/anandaravindan/macd.
Thanks

**Comment by KashyapCKotak** [comment]
Can anyone please reply to my question above? I am really confused.

**Comment by anandanand84** [comment]
If you pass 61 data points and you set the period to 25 you will get only 36 data, it is because to calculate on data point of sma you need 25 data points. So you will always get 61 - period number of data points back. if you want you can prepend 0 or null in front
