### ISSUE TITLE
Bollinger Bands NaN values in browser

### ISSUE THREAD

**Issue by StalexB** [anandanand84/technicalindicators#134]
Hello,

I'm encountering an issue where I get NaN values for upper and lower bollinger bands with input that normally does the job when using it in Node. This issue is most likely related to the browser I guess. Can you help me out?

![a813c1a02755b2f2a97c16e4cda55c3f](https://user-images.githubusercontent.com/16706921/40578788-75624bae-611a-11e8-8e54-fc45a1b6a498.png)

**Comment by anandanand84** [comment]
can you provide the inputs used?

**Comment by StalexB** [comment]
Thanks for the quick response. The inputs used are visible in the picture, at the top.

**Comment by anandanand84** [comment]
Could not reproduce

**Comment by Georgy45** [comment]
Hi,

I have the same thing directly in Node.

Searched a bit, and found out that for some reasons, the stDev var is not passed (it returns "undefined" in BollingerBands class).
I replaced stDev by 2 in the BollingerBands class, lines 828/829 of /dist/index.js, and now it works.

**Comment by elcilie** [comment]
Hey ppl. You both are passing a mispelled parameter. is stdDev, not stDev (one "d" missing after "st").
