### ISSUE TITLE
cryptotrading-hub.com rendering incorrectly in chrome

### ISSUE THREAD

**Issue by KashyapCKotak** [anandanand84/technicalindicators#135]
Hello, Thanks for this amazing first of all. While looking at examples on cryptotrading-hub.com, I found that  the chart area on top and on right persisted anything that was displayed there previously. See the screenshot below:

![image](https://user-images.githubusercontent.com/20476571/40588740-f795c700-61ff-11e8-84fa-70073dd186ab.png)

I did not behave this way a few days back. Thought to make it notice to you.

Also I have another doubt and would be grateful if you help me out. This question may be a dumb one but is really confusing me: When I pass data to MACD (SMA), which has 61 data points, only 36 MACD data points are returned. Shouldn't it be 61 data points returned? or am I missing something?

The code I am using to test is what you provided at https://tonicdev.com/anandaravindan/macd.

Thanks again.

**Comment by anandanand84** [comment]
@KashyapCKotak Lets continue the conversation about cryptotrading-hub.com on discord or reddit and keep only technicalindicator related stuff in here. Can you send me a message in discord. I'll close this. Thanks.
