### ISSUE TITLE
Have some error in QQ browser 9.xx

### ISSUE THREAD

**Issue by hnlinzhi19** [anandanand84/technicalindicators#147]
when my web in QQ browser 9 , first error ** is not support ,sende async error.

**Comment by anandanand84** [comment]
which file did you use? I am not sure what browser is it and what capabilities it supports
Try this file
https://raw.githubusercontent.com/anandanand84/technicalindicators/master/dist/browser.js
if it did not work you have to compile for that browser from the src using babel
