### ISSUE TITLE
Stochastic RSI example not found

### ISSUE THREAD

**Issue by Fab85** [anandanand84/technicalindicators#149]
Hello,

I wanted to calculate the Stochastic RSI, but the link to the example code shows 404. How do I use the Stochasitc RSI in my code?

Thanks

**Comment by anandanand84** [comment]
You can look at the src/ folder or the test folder to see an example.

stochasticrsi({
  values : number[];
  rsiPeriod:number;
  stochasticPeriod:number;
  kPeriod:number;
  dPeriod:number;
})
