### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by furkankinyas** [anandanand84/technicalindicators#150]
https://runkit.com/anandaravindan/stochasticrsi 
do you have sample code about stochasticrsi

**Comment by anandanand84** [comment]
You can take a look at the source code for the input and output

https://github.com/anandanand84/technicalindicators/blob/master/src/momentum/StochasticRSI.ts#L12

```
stochasticrsi({
  values : number[];
  rsiPeriod:number;
  stochasticPeriod:number;
  kPeriod:number;
  dPeriod:number;
})
```
