### ISSUE TITLE
Time in "Volume Profile" indicator result

### ISSUE THREAD

**Issue by dawadam** [anandanand84/technicalindicators#151]
Hi
I do not understand why there is a value "time" in the result of the indicator.
What is the interest? How is it used?

**Comment by anandanand84** [comment]
@dawadam  Here is the source code for volume profile, where do you see the time in the results

https://github.com/anandanand84/technicalindicators/blob/master/src/volume/VolumeProfile.ts

**Comment by dawadam** [comment]
@anandanand84 Sorry, it's an error...
