### ISSUE TITLE
Quick question about pattern detection training 

### ISSUE THREAD

**Issue by sullyfischer** [anandanand84/technicalindicators#152]
I'm looking to train a few models using Tensorflow, let's say (I'm not sure yet) for more candlestick patterns. Could you please let me know from your experience, how many examples of each chart pattern I would need for the model to work accurate enough? 10? 100? 1000? 10000? You see where this is going 😆

**Comment by anandanand84** [comment]
Candlestick patterns has clear logic to identify, so it would be better to find candlestick patterns in traditional programming. I am assuming you are trying to identify chart patterns which is complicated, I used to get good results with tens of thousands of patterns, I mostly used a combination of synthetic and organic data. Getting the organic data is the key for accurate prediction which is very difficult
