### ISSUE TITLE
tensorflow/core/platform/cpu_feature_guard.cc with technicalindicators.ADX

### ISSUE THREAD

**Issue by nedievas** [anandanand84/technicalindicators#153]
> I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA

**Comment by pigd0g** [comment]
I get the same, just a warning I think, would be nice to remove from logs.

**Comment by anandanand84** [comment]
Tensorflow removed in 3.0. It should work now
