### ISSUE TITLE
Ichimoku cloud should be having lagging span line also?

### ISSUE THREAD

**Issue by KashyapCKotak** [anandanand84/technicalindicators#156]
While provinding the input for Ichimoku, I can see a displacement option. While referring Investopedia (https://www.investopedia.com/terms/i/ichimoku-cloud.asp) and StockCharts (https://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:ichimoku_cloud) I can see an extra line plotted by the name of Chikou Span or Lagging Span. Can this line please be added in Ichimoku cloud indicator?

I must say this is an awesome library and I really respect the effort you've put in already! Thanks!

**Comment by anandanand84** [comment]
@KashyapCKotak Chikuspan is a displacement of the close, there is nothing to add in that. For getting the chikuspan you just use close[i - displacement]. For example with displacement value of 1. Close of today is the chikuspan for yesterday
