### ISSUE TITLE
Reliance on tensorflow problematic

### ISSUE THREAD

**Issue by rd13** [anandanand84/technicalindicators#157]
Tensor flow reliance is a complete nightmare when using in any environment with node or compiling with webpack for the browser.

Node:

Nodejs Environment detected
2018-11-22 11:42:26.099821: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
(node:85351) UnhandledPromiseRejectionWarning: ReferenceError: tf is not defined

webpack:

[es]     WARNING in ./node_modules/bindings/bindings.js 81:22-40
[es]     Critical dependency: the request of a dependency is an expression
[es]      @ ./node_modules/@tensorflow/tfjs-node/dist/index.js
[es]      @ ./node_modules/technicalindicators/lib/patterndetection/patterndetection.js
[es]      @ ./node_modules/technicalindicators/lib/index.js

[es]     WARNING in ./node_modules/bindings/bindings.js 81:43-53
[es]     Critical dependency: the request of a dependency is an expression
[es]      @ ./node_modules/@tensorflow/tfjs-node/dist/index.js
[es]      @ ./node_modules/technicalindicators/lib/patterndetection/patterndetection.js
[es]      @ ./node_modules/technicalindicators/lib/index.js

**Comment by hungryforcodes** [comment]
Yeah, I get the same "ReferenceError: tf is not defined" on startup.

**Comment by anandanand84** [comment]
It is fixed in technicalindicators@2.0.7. Please verify

**Comment by jsappme** [comment]
i am still getting ```2019-04-13 13:13:07.368884: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
``` using 2.0.7
