### ISSUE TITLE
CCI using 20 instead of input

### ISSUE THREAD

**Issue by itraderobots** [anandanand84/technicalindicators#161]
The CCI is using the number 20 instead of the input, which is an issue for anyone who wants to use a CCI period other than 20. I change it manually to reference the CCI period I needed to use by replacing the number 20 with input.period and it worked, although there is probably some other way you prefer. 

It needs to be changed to use the input provided by the programmer in these two places:

https://github.com/anandanand84/technicalindicators/blob/718cabf3d763109bb844569d348a3054b3d9d9e6/lib/oscillators/CCI.js#L40

https://github.com/anandanand84/technicalindicators/blob/718cabf3d763109bb844569d348a3054b3d9d9e6/dist/index.js#L1889

**Comment by anandanand84** [comment]
Thank you. I will fix it.

**Comment by RomanKisilenko** [comment]
Hi, please make this fix.

**Comment by anandanand84** [comment]
Fixed and published

**Comment by RomanKisilenko** [comment]
Thank you!
