### ISSUE TITLE
how to use with Promise or callback

### ISSUE THREAD

**Issue by SouthRibbleTech** [anandanand84/technicalindicators#163]
I am struggling to use this library in my use case. I have an array of symbols that I map through and for each symbol I want to use the SMA function. The problem is that I have no way to wait for the calculation to finish on each symbol before calculating the next one. 

Am I missing something? I have looked everywhere for examples of a callback function that I can promisify with bluebird.

**Comment by anandanand84** [comment]
The API is synchronous. You dont need a promise or callback.
