### ISSUE TITLE
duplicated declarations

### ISSUE THREAD

**Issue by hariseldon78** [anandanand84/technicalindicators#166]
Hello, there is still a problem with duplicated declarations in the generated.d.ts:

```
export {FixedSizeLinkedList };

/**
  * Created by AAravindan on 5/7/16.
  */
export class FixedSizeLinkedList extends LinkedList {
    size: number;
```
so i fixed the problem to the root with this merge request: https://github.com/anandanand84/technicalindicators/pull/165

**Comment by anandanand84** [comment]
Merged and published
