### ISSUE TITLE
ATR indicator does not work properly

### ISSUE THREAD

**Issue by angryhorse0905** [anandanand84/technicalindicators#167]
https://github.com/anandanand84/technicalindicators/blob/master/test/directionalmovement/ATR.js

In this test file, atr.nextValue() param is object of high, low, close prices.
But the param type of nextValue() in ATR is number.

**Comment by anandanand84** [comment]
Agree, It is an issue with the typings. The test case is correct. You should use high, low, close price to make it work.

**Comment by anandanand84** [comment]
Fixed declarations
