### ISSUE TITLE
Cannot import into react

### ISSUE THREAD

**Issue by jslok** [anandanand84/technicalindicators#183]
Is there a specific method I need to use to use this in react?

I use any of the examples like so
`const sma = require('technicalindicators').sma;
var prices = [1,2,3,4,5,6,7,8,9,10,12,13,15];
var period = 10;
sma({period : period, values : prices})`

I get this error:
`./node_modules/@tensorflow/tfjs-data/dist/tf-data.esm.js
Attempted import error: 'deprecationWarn' is not exported from '@tensorflow/tfjs-core'.`

**Comment by MohamedLamineAllal** [comment]
Same here !

**Comment by anandanand84** [comment]
Tensorflow removed as part of 3.0
