### ISSUE TITLE
Allow to use the module without requiring Tensorflow backend

### ISSUE THREAD

**Issue by NotAlfred** [anandanand84/technicalindicators#188]
I'm regularly using your module which is very useful overall
There is one pain point though: I never need to use the pattern recognition features and having to load to whole tensorflow backend to just end up using some MACDs or RSIs is quite cumbersome.
I worked around that issue by forking your repository and completely getting rid of the tensorflow and pattern recognition components but it would be great to have official support for that

Thanks in advance

**Comment by jaggedsoft** [comment]
+1

**Comment by rjbernaldo** [comment]
+1

**Comment by jsappme** [comment]
+1

**Comment by NotAlfred** [comment]
Since there's demand for it, here's the repo I made: https://github.com/NotAlfred/technicalindicators

**Comment by anandanand84** [comment]
Tensorflow removed as part of 3.0
