### ISSUE TITLE
MACD

### ISSUE THREAD

**Issue by krokhale** [anandanand84/technicalindicators#190]
Just trying to wrap my head around this. Any help will be appreciated!  I have a pretty simple data set:

    [{minute: 1, closing: 112}, {minute: 2, closing: 112.5},...]

and so on.

According to the docs for MACD:

        let macdInput = {
                    values            :[112, 112.5],
                    fastPeriod        : 12,
                    slowPeriod        : 26,
                    signalPeriod      : 9,
                    SimpleMAOscillator: false,
                    SimpleMASignal    : false,                
                };

Is my assumption for values in macd input correct? I am just plugging in the closing prices for each minute in there as shown above in my sample data.

Am i missing something?

**Comment by anandanand84** [comment]
yes it is correct.

**Comment by krokhale** [comment]
Thanks!
