### ISSUE TITLE
cpu backend was already registered. Reusing existing backend 2019-08-30 11:35:08.543144: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2

### ISSUE THREAD

**Issue by iamweilee** [anandanand84/technicalindicators#193]
hi, the lib give warning when running:
`
cpu backend was already registered. Reusing existing backend
2019-08-30 11:35:08.543144: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
`

how fix it? thks.

**Comment by ofarukcaki** [comment]
Same error, any solution?

**Comment by anandanand84** [comment]
Tensorflow removed with version 3.0. This should not be an issue anymore.
