### ISSUE TITLE
generator function not supported by IOS or Opera etc

### ISSUE THREAD

**Issue by debsush** [anandanand84/technicalindicators#2]
Hi,

The generator function may not be supported by some of the web and mobile browsers as per below link.  Is this correct?

[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#iterable](url)

Is yes, was wondering if we could replace the generator function with something more generic which can be supported by almost all common browsers.  It would far outweight the convenience of using the generator function.

Let me know your thoughts

Regards

**Comment by anandanand84** [comment]
There is a browser version available at dist/browser.js which works in all the browsers, did you try that?

https://github.com/anandanand84/technicalindicators/blob/master/dist/browser.js

**Comment by debsush** [comment]
No, I must admit I did not.  Thanks for this one.  Can you please explain what does the browser.js do.  Does it make the generator function compatible across browsers or is it a rewritten indicator function which uses generic JS syntax which is compatible across browsers.  

Appreciate if you could give a summary of the concept behind the browser.js  I realized deciphering the functionality of browser.js would take a significant time at my end.  Also, explanation of the functionality from the creator would help enhance the documentation of the package

Regards

**Comment by debsush** [comment]
I think I understand the use of Babel.  Thank you
