### ISSUE TITLE
EMA and SMA returns the same values

### ISSUE THREAD

**Issue by xmspix** [anandanand84/technicalindicators#204]
EMA and SMA with same period returns the same result

**Comment by xmspix** [comment]
sorry it was my mistake i didn't reverse the close prices

**Comment by tusharsinghal1610** [comment]
It still gives the same output, how did you resolve?

**Comment by xmspix** [comment]
hi, you should try to reverse the data...

in my case i take stocks data from yahoo, here is what i did and it worked :

export const SMA = ({ values, period }) => {
return Indicator.SMA.calculate({
period: period,
values: values.reverse()
}).reverse()[0];
};

export const EMA = ({ values, period }) => {
return Indicator.EMA.calculate({
period: period,
values: values.reverse()
}).reverse()[0];
};

**Comment by tusharsinghal1610** [comment]
I have my data suppose [4,5,6,7,8,9]
if i use period 4
EMA gives = 7.5 (just the simple average of last four)
SMA gives = 5.5 (just the simple average of first four) 

actually when you are using reverse() inside function , it reverses array two times , thus gives different averages one starting , and one ending
