### ISSUE TITLE
How to update the last bar indicators?

### ISSUE THREAD

**Issue by QuantBull** [anandanand84/technicalindicators#231]
Hi @anandanand84:
I can append the newest bar with calling indic.nextValue. But if not append , just only want to update the last bar with the newest bar data which have the same xAxis value, how to coding? Are there some tips.

**Comment by iamweilee** [comment]
I want to pop the last data from the linklist and calling indic.nextValue with the newest data, but I don't know how to pop. I can't operate the linklist directly.
