### ISSUE TITLE
Stochastic not correct?

### ISSUE THREAD

**Issue by indexofrefraction** [anandanand84/technicalindicators#240]
GOOG 2021 May 12th
technicalindicators --> Stochastic d=24.75, k=4.06 (using period=14, signalPeriod=3)
Yahoo Finance --> Stochastic d=24.75, k=44.1

**Comment by indexofrefraction** [comment]
ok.. my bad... if you turn off "smooth" in yahoo, then k is 4.06, too

**Comment by tvdaredevil** [comment]
Close the issue!

**Comment by ezcafe** [comment]
How to use smooth with Stochastic?
