### ISSUE TITLE
Separate candles with bearish and bullish

### ISSUE THREAD

**Issue by chiu0602** [anandanand84/technicalindicators#26]
Some candle patterns such as Marubozu and Harami grouped bearish and bullish into one pattern. I think separating them into two should provide better usage for them.

**Comment by anandanand84** [comment]
yes there is plan to add a picture to find all bullish and bearish in one call as well

**Comment by anandanand84** [comment]
See https://github.com/anandanand84/technicalindicators/blob/master/lib/candlestick/Bullish.js
