### ISSUE TITLE
TypeError: Cannot read property 'hasPattern' of undefined

### ISSUE THREAD

**Issue by linnya** [anandanand84/technicalindicators#39]
Hi everyone, when I test any example of candlesticks patterns

I get same error:

`TypeError: Cannot read property 'hasPattern' of undefined`

```
Node version: 6.9.5
technicalindicators": ^0.2.24
OS: WINDOWS 10 ;D
```
![error](https://cloud.githubusercontent.com/assets/19173666/24324738/63c67b1e-116a-11e7-8249-516db18ad74b.png)

ty

**Comment by anandanand84** [comment]
Hi

Please look https://github.com/anandanand84/technicalindicators/issues/38 and let me know if that solves your issue.

**Comment by linnya** [comment]
sorry for duplicate issue, i tried with lowercase

My code:
```
var AbandonedBaby = require('technicalindicators').abandonedBaby;
var drawCandleStick = require('draw-candlestick');
var canvas = require('canvas');

var threeDayInput = {
  open: [31.10,26.18,27.47],
  high: [31.80,26.91,30.94],
  close: [28.10,26.18,30.62],
  low: [27.50,25.40,27.03]
};

var imageBuffer = drawCandleStick(threeDayInput);
console.log(imageBuffer);
var result = AbandonedBaby.hasPattern(threeDayInput);
console.log('Is Abandoned Baby : '+ result);
```

Thank you ;)

**Comment by linnya** [comment]
Solved ;)

`var AbandonedBaby = require('technicalindicators').abandonedbaby;
var drawCandleStick = require('draw-candlestick');
var canvas = require('canvas')

var threeDayInput = {
  open: [31.10,26.18,27.47],
  high: [31.80,26.91,30.94],
  close: [28.10,26.18,30.62],
  low: [27.50,25.40,27.03]
}
var imageBuffer = drawCandleStick(threeDayInput);
console.log(imageBuffer);
// dont use .hasPattern
var result = AbandonedBaby(threeDayInput);
console.log('Is Abandoned Baby : '+ result);`
