### ISSUE TITLE
[Webpack v2] Module not found: Error: Recursion in resolving

### ISSUE THREAD

**Issue by roblav96** [anandanand84/technicalindicators#40]
Hello mate,

Today I've been migrating my playground/sandbox over to webpack 2.0 and I can't get `technicalindicators` to resolve properly =[

It yells at me:
```
ERROR in ./~/technicalindicators/lib/moving_averages/SMA.js
Module not found: Error: Recursion in resolving
```
Here's a gist
https://gist.github.com/roblav96/e36937c29384db5530164e7373b2a1e5
of the full log and the `webpack.config.js`. (I hate when people leave absurdly long console.logs in the OP)

Any idea what could be the issue? I'm gonna keep looking into this and I'll let you know if I can resolve it.

Cheers!

**Comment by knoopx** [comment]
I have the same problem, seems like the `main` entry from `linkedlist`'s `package.json` is incorrect. You can workaround the problem by adding an alias to you webpack config:

```
  resolve: {
    ...
    alias: {
      linkedlist: 'linkedlist/lib/linkedlist.js',
    },
  },
```

**Comment by roblav96** [comment]
@knoopx You are so winning!!! Thanks mate.
