### ISSUE TITLE
MACD strange behavior

### ISSUE THREAD

**Issue by Neabfi** [anandanand84/technicalindicators#43]
Hello,

I calculate two MACD with the following settings. The first time I just remove the 5 oldest data. Why this affect the most recent MACD ? There is a small difference:
MACD: 7.10857, signal: 7.10857 vs  MACD: 7.10239, signal: 7.10239
Thanks !

```
var macdInput = {
  values            : [ length: 200 ],
  fastPeriod        : 4,
  slowPeriod        : 6,
  signalPeriod      : 2,
  SimpleMAOscillator: false,
  SimpleMASignal    : false
}
```

```
var macdInput = {
  values            : [length: 205],
  fastPeriod        : 4,
  slowPeriod        : 6,
  signalPeriod      : 2,
  SimpleMAOscillator: false,
  SimpleMASignal    : false
}
```

**Comment by anandanand84** [comment]
could not understand your issue? can you post a complete example with data? Is the difference  is at the start or at end? Are you using reversedInput?

**Comment by Neabfi** [comment]
Here is a simple exemple:

```
var MACD = require('technicalindicators').MACD;


var macdInput1 = {
  values            : [127.75,129.02,132.75,145.40,148.98,137.52,147.38,139.05,137.23,149.30,162.45,178.95,200.35,221.90,243.23,243.52,286.42,280.27],
  fastPeriod        : 5,
  slowPeriod        : 8,
  signalPeriod      : 3 ,
  SimpleMAOscillator: false,
  SimpleMASignal    : false
}

var result1 = MACD.calculate(macdInput1);



var macdInput2 = {
  values            : [1, 127.75,129.02,132.75,145.40,148.98,137.52,147.38,139.05,137.23,149.30,162.45,178.95,200.35,221.90,243.23,243.52,286.42,280.27],
  fastPeriod        : 5,
  slowPeriod        : 8,
  signalPeriod      : 3 ,
  SimpleMAOscillator: false,
  SimpleMASignal    : false
}

var result2 = MACD.calculate(macdInput2);

console.log(result1[result1.length-1]);
console.log(result2[result2.length-1]);
```
Output:
```
{ MACD: 20.01256, signal: 18.71726, histogram: 1.29531 }
{ MACD: 21.00916, signal: 20.06599, histogram: 0.94317 }
```

I juste add a 1 at the beginning of macdInput2.values.
Why the last value of result1 and result2 are not the same ?
(I'm not using reversedInput)

**Comment by anandanand84** [comment]
@Neabfi This seems to be working as expected. MACD is calculated based on moving average of moving average so if you provide values all the values are utilized for every result and it is not like SMA where only the last value depends only on the last 8 values.

**Comment by Neabfi** [comment]
Oh yes indeed, my bad, thanks !
