### ISSUE TITLE
MACD calculation is wrong: should be (slow period - fast period) and not vice versa

### ISSUE THREAD

**Issue by dexbg** [anandanand84/technicalindicators#44]
The MACD value is reversed - i.e. the formula is (slow period - fast period) and not vice versa

**Comment by anandanand84** [comment]
Just verified it in wikipedia and stockcharts.com both use fast - slow.

https://en.wikipedia.org/wiki/MACD

http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:moving_average_convergence_divergence_macd

**Comment by anandanand84** [comment]
@dexbg If you find this correct you can close the issue, else provide me a resource and we can discuss and if it is correct I am happy to change.

**Comment by dexbg** [comment]
Sorry, my mistake.

**Comment by heekah7** [comment]
dexbg, I cannot thank you enough for the amazing library. Unfortunately, anandanand84 is right, when I compare the generated MACD is different from Yahoo financial. Maybe they're wrong but it worths investigating.

**Comment by anandanand84** [comment]
@heekah7 can you send me a screenshot of the difference, did you look at cryptocurrency or other?
Can you check if yahoo finance is different from https://cryptotrading-hub.com if it is cryptocurrency, cryptotrading hub uses this library

**Comment by anandanand84** [comment]
I just verified against trading view it seems to be correct, can you verify again if the parameters are the same with both yahoo and the library

![screen shot 2017-12-08 at 12 36 37 pm](https://user-images.githubusercontent.com/5538452/33780029-d533ef00-dc14-11e7-967b-c1aece3e03e7.png)
![screen shot 2017-12-08 at 12 36 27 pm](https://user-images.githubusercontent.com/5538452/33780033-d917fb84-dc14-11e7-9fff-d197235db0aa.png)

**Comment by jsappme** [comment]
I am not able to get the same MACD between binance and this MACD value. Is this formula right?

**Comment by anandanand84** [comment]
It uses the formula from http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:moving_average_convergence_divergence_macd and it has test cases from stock charts if it has one. If you see an issue in the code, I am happy to change it.

**Comment by anandanand84** [comment]
Can you send your calculation, I see it is the same with binance and this library?
![image](https://user-images.githubusercontent.com/5538452/35475503-3c9fe0dc-0365-11e8-9d99-51b407a030e5.png)

**Comment by anandanand84** [comment]
@jsappme @jaggedsoft https://cryptotrading-hub.com uses the technical indicators from this library and it seems to match with binance. Can you compare the two charts you may be comparing the wrong parameters.

**Comment by jaggedsoft** [comment]
@anandanand84 I couldn't say for sure, seems to work great. I love this library, thanks for sharing.

**Comment by anandanand84** [comment]
@jsappme I did go through the code again since there were lot of people reporting this, I did find out an issue. By default it uses simple moving average that is where people get confused. 

try below 
```
macd({
    values            : [] //close prices
    fastPeriod        : 5,
    slowPeriod        : 8,
    signalPeriod      : 3,
    SimpleMAOscillator: false, //this defaults to true that is where the problem is
    SimpleMASignal    : false, //this defaults to true that is where the problem is
})
```
Feel free to reopen the issue if you find a mismatch after using simple ma as false.

**Comment by anandanand84** [comment]
You can also use ```reversedInput```

```
var macdInput = {
   reversedInput : true
}
```
