### ISSUE TITLE
Rate of Change Drops 0 values

### ISSUE THREAD

**Issue by roblav96** [anandanand84/technicalindicators#46]
### Runkit Example
https://runkit.com/roblav96/5945db28f7965000121d9545
Result `[79]` should be a 0 at `April 28, 2017`
https://www.tradingview.com/chart/auBuV2o7/
So it looks like the calc is dropping `0`'s completely.

**Comment by anandanand84** [comment]
@roblav96 I couldn't get the issue, the tradingview chart you linked shows only ADX, there is no ROC in there. Did you linked a wrong chart?

**Comment by roblav96** [comment]
@anandanand84 Sorry late reply :X
Idk how to share the exact view. A bit over complicated UX design. I guess this one's a bust.

**Comment by anandanand84** [comment]
@roblav96 This should be fixed. Can you check with latest version?
