### ISSUE TITLE
Using the latest data instead the first of the array

### ISSUE THREAD

**Issue by eugenioclrc** [anandanand84/technicalindicators#48]
In the logic of the Candlestickfinders you are using the first element of the data, instead the latest, example;
https://github.com/anandanand84/technicalindicators/blob/master/src/candlestick/MorningStar.ts#L10

I think i shoul look something like;
```

logic (data:StockData) {
    const firstDay = data.length - 3;
    const secondDay = data.length - 2;
    const thirdDay = data.length - 1;

    let firstdaysOpen   = data.open[firstDay];
    let firstdaysClose  = data.close[firstDay];
    let firstdaysHigh   = data.high[firstDay];
    let firstdaysLow    = data.low[firstDay]
    let seconddaysOpen  = data.open[secondDay];
    let seconddaysClose = data.close[secondDay];
    let seconddaysHigh  = data.high[secondDay];
    let seconddaysLow   = data.low[secondDay]
    let thirddaysOpen   = data.open[thirdDay];
    let thirddaysClose  = data.close[thirdDay];
    let thirddaysHigh   = data.high[thirdDay];
    let thirddaysLow    = data.low[thirdDay];
     
```

**Comment by anandanand84** [comment]
@eugenioclrc if your inputs is reversed you can use reversedInput:true in the data you pass.

see below.

https://github.com/anandanand84/technicalindicators/blob/master/src/candlestick/CandlestickFinder.ts#L43

**Comment by eugenioclrc** [comment]
.reverse() is different than use the latest elements of the array

[0,1,2,3,4,5,6].reverse() => [6,5,4,3,2,1,0]

data = [0,1,2,3,4,5,6]
data.slice(data.length - 3) => [4,5,6]

**Comment by anandanand84** [comment]
@eugenioclrc 
<img width="739" alt="screen shot 2017-06-18 at 3 25 30 pm" src="https://user-images.githubusercontent.com/5538452/27263947-8a4572e6-543a-11e7-83b1-b66d13845f88.png">
<img width="733" alt="screen shot 2017-06-18 at 3 25 39 pm" src="https://user-images.githubusercontent.com/5538452/27263948-931e0360-543a-11e7-9b68-d39d13ba50ca.png">

It looks good to me. Can you elaborate what is the issue ? It would be helpful if you can plot an image using draw-candlestick to explain the issue?

Also checkout this line to see if it solves your concern.

https://github.com/anandanand84/technicalindicators/blob/master/src/candlestick/CandlestickFinder.ts#L65
