### ISSUE TITLE
[FYI] Node.js and indicators

### ISSUE THREAD

**Issue by vlad-saling** [anandanand84/technicalindicators#49]
Hi,

thank you for this module! It saves quite a lot of time and coding. While implementing it inside an Node.js app I've noticed that this `const SMA = require('technicalindicators').SMA` isn't working. Upon calling SMA it throws "undefined". I looked a bit into the code and it works if I do this: 
`const SMA = require('technicalindicators').window.SMA`

Not sure if you want/need to update your docs, but I've figured somebody might find this useful when searching issues.

Feel free to close this issue right away or let me know if I am doing something wrong.

**Comment by anandanand84** [comment]
you're right. Currently there is an issue, i need to figure out a way to compile for both nodejs and browser

**Comment by anandanand84** [comment]
Added better support for nodejs. This is fixed in version 1.0.5. Thanks for pointing out.  Please verify

**Comment by vlad-saling** [comment]
Thank you for resolving this so quickly 👍. I've tested latest release and it is now working according docs.

You can close this issue.
