### ISSUE TITLE
PlusDM MinusDM

### ISSUE THREAD

**Issue by ramonescamilla** [anandanand84/technicalindicators#51]
How can I add the plusDM and minusDM points added to my adx points? 

Thanks,

Ramon

**Comment by anandanand84** [comment]
@ramonescamilla I havent added the ADX yet. Will add it soon.

**Comment by anandanand84** [comment]
ADX along with +DI and -DI added see https://github.com/anandanand84/technicalindicators/blob/master/test/directionalmovement/ADX.js
