### ISSUE TITLE
Number accuracy

### ISSUE THREAD

**Issue by josephfinlayson** [anandanand84/technicalindicators#53]
Using simple numbers in JS can lead to rounding errors. Have you thought about using BigNumber js?

**Comment by anandanand84** [comment]
@josephfinlayson I am not sure about where there is rounding errors, can you show me a simple example where it fails, if necessary we can use BigNumberjs

**Comment by anandanand84** [comment]
@josephfinlayson I added this in readme, I thought about the BigNumbers and it really is a big change that affects every indicator and every file with a very little benefit. I also added below in the readme.

```
This uses regular javascript numbers, so there can be rounding errors which are negligible for a technical indicators, you can set precision by using the below config. By default there is no precision set.

const technicalIndicators = require('technicalindicators');
technicalIndicators.setConfig('precision', 10);
```

If you think otherwise, reopen the issue and we can discuss.

Thanks

**Comment by josephfinlayson** [comment]
e.g:

    var x = 0.1 * 0.2;
    console.log(x) // 0.020000000000000004
