### ISSUE TITLE
Renko Chart

### ISSUE THREAD

**Issue by balupton** [anandanand84/technicalindicators#54]
I'm quite a fan of [Renko Charts](https://www.tradingview.com/wiki/Renko_Charts) and been looking for a library that does them. I've found that [react-stockcharts](https://github.com/rrag/react-stockcharts) does [renko](https://github.com/rrag/react-stockcharts/blob/b9518ad87bb29b39d79b5b80ab9c8dc406294c15/src/lib/calculator/renko.js) as well as many others.

What is the feasibility of adding support for Renko and other chart types to this library?

**Comment by anandanand84** [comment]
@balupton It can be added, if possible can you provide test cases for renko, with ATR and traditional.

**Comment by anandanand84** [comment]
Renko charts added.
