### ISSUE TITLE
RSI calculation returns no value

### ISSUE THREAD

**Issue by stylixboom** [anandanand84/technicalindicators#57]
With RSI period of 14, the calculating RSI for the following values return nothing
[ 294435,  294435,  294435,  294500,  294500,  294500,  294520,  294539,  294539,  294600,  294600,  294600,  294600,  294600,  294700 ]

but when I change some value to be
[ 294435,  294435,  294435,  294500,  294500,  **294400**,  294520,  294539,  294539,  294600,  294600,  294600,  294600,  294600,  294700 ]
RSI returns -> 78.49

I'm not sure in which condition RSI return nothing,
should this problem be handled by input pre-validation or output post-correction.
(or if this a bug?)

**Comment by anandanand84** [comment]
@stylixboom It is possibly a bug when the first two numbers are the same. I'll look at it. Thanks

**Comment by cynanrhodes** [comment]
If, when calculating RSI for a given set of prices, every increment gains (or loses), then there is a divide by zero error.

In the above example, when 294500 was changed to 294400 the number of loses went from 0 to 1 and so the division works.
