### ISSUE TITLE
Average Directional Index example dead link on readme

### ISSUE THREAD

**Issue by oeed** [anandanand84/technicalindicators#58]
Not a huge issue really, it's easy to figure out by looking at the source, but the link for the ADX example in the readme appears to be dead.

**Comment by stylixboom** [comment]
I think, at the moment, you can find an ADX example through the test source here
https://github.com/anandanand84/technicalindicators/blob/master/test/directionalmovement/ADX.js

But yes, the link for ADX in the readme is dead.

**Comment by anandanand84** [comment]
Fixed. Linked to the test.
