### ISSUE TITLE
indentation rules

### ISSUE THREAD

**Issue by balupton** [anandanand84/technicalindicators#61]
seems there is some inconsistent indentation going on - javascript files in `test` are at 2 space indentation, whereas typescript files in `src` are at 4 space indentation

`src/chart_types/Renko.ts` also has mixed indentation

I'd suggest the following `.editorconfig` file to resolve this:

```
# editorconfig.org
root = true

[*]
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = false
indent_style = space
indent_size = 4

[*.mk]
indent_style = tab

[*.md]
indent_style = space
indent_size = 4

[{*.json,*.yml,*.bowerrc,*.babelrc}]
indent_style = space
indent_size = 2
```

VSCode plugin for EditorConfig: https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

**Comment by anandanand84** [comment]
sure. I'll add it when I commit next, or you can add if you are planning for any pull request.

**Comment by anandanand84** [comment]
actually can you add it along with the this pull request https://github.com/anandanand84/technicalindicators/pull/60

**Comment by balupton** [comment]
done
