### ISSUE TITLE
Trouble using CCI

### ISSUE THREAD

**Issue by jaggedsoft** [anandanand84/technicalindicators#62]
Hi, thanks for this awesome library. You rock!

Having trouble getting CCI working in the latest release `10.0.16`
`const CCI = require('technicalindicators').CCI;`
TypeError: Cannot read property 'calculate' of undefined

`const CCI = require('technicalindicators/lib/oscillators/CCI').CCI;`
(function (exports, require, module, __filename, __dirname) { import { Indicator, IndicatorInput } from '../indicator/indicator';
                                                              ^^^^^^
SyntaxError: Unexpected token import

Thanks in advance!!

**Comment by anandanand84** [comment]
Fixed. It was not added in the index. It should work in latest release. use
const CCI = require('technicalindicators').CCI
or 
const cci = require('technicalindicators').cci
