### ISSUE TITLE
Typescript errors 

### ISSUE THREAD

**Issue by cynanrhodes** [anandanand84/technicalindicators#63]
I'm coming across the following: 

node_modules/technicalindicators/declarations/chart_types/HeikinAshi.d.ts(14,22): error TS2415: Class 'HeikinAshi' incorrectly extends base class 'Indicator'.
  Types of property 'result' are incompatible.
    Type 'CandleList' is not assignable to type 'any[]'.
      Property 'length' is missing in type 'CandleList'.

**Comment by mingoal** [comment]
same issue with version 1.0.17
