### ISSUE TITLE
[Q] Period unit

### ISSUE THREAD

**Issue by Sneakware** [anandanand84/technicalindicators#64]
Hi, first off, thanks for this lib!

I'm not really familiar with TA, so pardon if it sounds like dumb questions.
Could you tell me what the unit the period integer refers to? Even after looking at the code and examples I can't really grasp it. Also, the values are the different close values for said period right?

Thanks!

**Comment by anandanand84** [comment]
@Sneakware Period is number, For example: for moving average period is the average period. You can look at the examples https://tonicdev.com/anandaravindan/sma

**Comment by anandanand84** [comment]
@Sneakware yes values are different close values if you want to take average of close

**Comment by Sneakware** [comment]
Hum ok, so the period is actually the number of average period you want to construct with the data you are providing? I've tried a few things and still don't get [this result](https://runkit.com/sneakware/59926970dd54dd001212bcb1) though, isn't it supposed to be `[1.5, 2.5, 3.5, 4.5]`? Also with a period of `1`, I would assume the result is the initial input, and not an array filled with 1's, is that just an unhandled case?

**Comment by anandanand84** [comment]
@Sneakware  you are right thats an unhandled case.
