### ISSUE TITLE
Use it with react

### ISSUE THREAD

**Issue by lionel95200x** [anandanand84/technicalindicators#70]
Hello
I can't use this module with react, the SMA value is undefined when i launch the exemple

Can you help me ? Have you solution to use it with react js ?

Thanks

**Comment by anandanand84** [comment]
@lionel95200x sure. are you using some kind of module bundler?

Can you check if this helps 

https://github.com/anandanand84/technicalindicators/issues/50#issuecomment-314141400

**Comment by lionel95200x** [comment]
No i have the same error "browser.js:1 Uncaught ReferenceError: regeneratorRuntime is not defined"

I import  this at the top of the file but this not work
require('babel-polyfill')
const SMA = require('technicalindicators').SMA;

Can you help me ?

**Comment by lionel95200x** [comment]
I solve this using :
const SMA = require('technicalindicators/dist').SMA
