### ISSUE TITLE
Reversing Inputs

### ISSUE THREAD

**Issue by JMoli** [anandanand84/technicalindicators#71]
Love the library! Thanks for all the hard work! I am trying to understand if I should be reversing my Inputs or not, and was hoping to get some clarification on what I should be understanding! Thanks again!

[Stochastic](https://github.com/anandanand84/technicalindicators/blob/02a270e56cad28ffa458ebf8c4d683a9161cb55b/src/momentum/Stochastic.ts#L96
)

    export function stochastic(input:StochasticInput):StochasticOutput[] {
        Indicator.reverseInputs(input); //First Reverse Input Check
        var result = new Stochastic(input).result;
        if(input.reversedInput) { //Reversed Input Boolean 
            result.reverse();  //Reversed Result
        }
        Indicator.reverseInputs(input); //Second Reverse Input Check After Input is Reversed
        return result;
    };

And in the [Indicator](https://github.com/anandanand84/technicalindicators/blob/02a270e56cad28ffa458ebf8c4d683a9161cb55b/src/momentum/Stochastic.ts#L96) Class 

     static reverseInputs(input:any):void {
        if(input.reversedInput) { //Same Reversed Input Boolean Check
            input.values ? input.values.reverse() : undefined;
            input.open ? input.open.reverse() : undefined;
            input.high ? input.high.reverse() : undefined;
            input.low ? input.low.reverse() : undefined;
            input.close ? input.close.reverse() : undefined;
            input.volume ? input.volume.reverse() : undefined;
            input.timestamp ? input.timestamp.reverse() : undefined;
        }
    }

As far as I can tell unless the  `reverseInput = true`nothing happens. So when `reverseInputs = true`  is the input being reversed twice? and the output reversed once? Is the input being reversed after the result is reversed and does that matter or just redundant? Sorry if I am missing something. Cheers!

**Comment by anandanand84** [comment]
@JMoli You may not need the reversedInput. It is used only when you array contains the latest data first(based on time) and the oldest data last.  You can check this issue for the reason for the second reverse. https://github.com/anandanand84/technicalindicators/issues/16

**Comment by JMoli** [comment]
#16 furthers the confusion? The code example listed is wrong?

    const technicalindicators = require('technicalindicators');
    const values = [0.001, 0.003, 0.001, 0.003, 0.004, 0.002, 0.003, 0.003, 0.002];
    console.log("before: " + values);
    const smaValues = technicalindicators.SMA.calculate({ reversedInput: true, period: 4, values: values });
    console.log("after: " + values);

Whereas the post indicated the results come out backwards and somehow jump scope and change our local variable seems like a user error more than a bug in the library.

    Expected output reversedInput = true:

     before: 0.001,0.003,0.001,0.003,0.004,0.002,0.003,0.003,0.002
     after: 0.001,0.003,0.001,0.003,0.004,0.002,0.003,0.003,0.002

     Actual output reversedInput = true::
     before: 0.001,0.003,0.001,0.003,0.004,0.002,0.003,0.003,0.002
     after: 0.001,0.003,0.001,0.003,0.004,0.002,0.003,0.003,0.002

and setting `reversedInput =  false` and running the same snippet again yields the same results as expected.
 
    Expected output reversedInput = false:

     before: 0.001,0.003,0.001,0.003,0.004,0.002,0.003,0.003,0.002
     after: 0.001,0.003,0.001,0.003,0.004,0.002,0.003,0.003,0.002

     Actual output reversedInput = false:
     before: 0.001,0.003,0.001,0.003,0.004,0.002,0.003,0.003,0.002
     after: 0.001,0.003,0.001,0.003,0.004,0.002,0.003,0.003,0.002


I believe there to be two things that are confused here. First, whether or not the `reverseInput` boolean is actually reversing the input, and whether or not that output needs to be reversed as well. I think from a functional perspective reversing input seems like a silly thing to abstract and this should be left to be done at the individual case level per developer specification. If I need my input reversed let me do it, and I will pass in what the technical library parameters are expecting. 

However, if I want the output to be reversed this seems like a function the library should encapsulate. +1 for refractoring `reverseInput` to `reverseOutput`

**Comment by anandanand84** [comment]
@JMoli, Well you got me confused :) Let me clarify for you.

First of it is not ```reverseInput```. It is ```reversedInput```.  It means the end user input is reversed and the library should calculate the indicators after reversing the input of the user.  Because calculating with the original reversed input will not give correct indicators especially for candlestick the order of the candles is important. So the library reverses the input, calculate the indicators and reverses again to make sure the input is not modified, so the user can use the same input array to different indicators or libraries. Before after in the #16 is basically he is saying the input should be not reversed after calculating the indicators.

If it creates more confusion for you, give me more information about your use case, most probably you may not need reverseInput and If you do I will be able to suggest what you need to do

**Comment by anandanand84** [comment]
@JMoli use reverseInput if your timestamp is descending, do not if it is ascending.

**Comment by JMoli** [comment]
I think I get it now, it needs to occur for things that are weighted?

**Comment by anandanand84** [comment]
yes, weighted averages will be wrong if we did not reverse before calculating the indicators.
