### ISSUE TITLE
Stochastic RSI

### ISSUE THREAD

**Issue by JMoli** [anandanand84/technicalindicators#72]
Anyone have any success doing this with RSI and Stochastic calculations of this library?

**Comment by anandanand84** [comment]
it should be very simple use FixedSizeLinkedList and Stochastic, you can write it yourself. or give me inputs and outputs to validate the test case and I can write that for you.

**Comment by bfischer1121** [comment]
Hi @anandanand84 what's FixedSizeLinkedList?

**Comment by anandanand84** [comment]
@bfischer1121 It is a data structure to be used. See https://github.com/anandanand84/technicalindicators/blob/master/src/momentum/Stochastic.ts#L7.

You can copy the stochastic implementation from here and replace to use RSI inplace of 

```
(Current Close - Lowest Low)/(Highest High - Lowest Low) * 100

```

to

```
StochRSI = (RSI - Lowest Low RSI) / (Highest High RSI - Lowest Low RSI)
````
To calculate RSI use this example

https://github.com/anandanand84/technicalindicators/blob/master/src/momentum/TRIX.ts#L24

**Comment by JMoli** [comment]
Is there a reason why the output from RSI run through stochastic does not work? Other than the first RSI value being zero?  Stochatic + RSI = Stochastic RSI? My results seem to be off.

**Comment by kappys1** [comment]
can you implement in next release?

**Comment by MaxSvargal** [comment]
+1
Yes, we can calculate it from another indicators, but stoch rsi is most usable thing. I think it must be out of the box.

**Comment by bfischer1121** [comment]
FWIW here's code to calculate Stoch RSI:
`
  const ti = require('technicalindicators');

  getStochRsi() // { k: [...], d: [...] }

  getStochRsi({ timePeriod=14, kPeriod=3, dPeriod=3 } = {}){
    let closes = [1, 2, 3, 4];

    return this.getRsi({ timePeriod }).then(rsi => {
      let fastK = [],
          prev, min, max;

      for(let i = timePeriod; i < rsi.length; i++){
        prev = rsi.slice((i + 1) - timePeriod, i + 1);
        min  = Math.min(...prev);
        max  = Math.max(...prev);

        fastK.push(((rsi[i] - min) / (max - min)) * 100);
      }

      let k = ti.SMA({ values: fastK, period: kPeriod }),
          d = ti.SMA({ values: k, period: dPeriod });

      return {
        k: k.slice(-1 * Math.min(k.length, d.length)),
        d: d.slice(-1 * Math.min(k.length, d.length))
      };
    });
  }
}
`

**Comment by MaxSvargal** [comment]
@bfischer1121 Can you make a PR, please?

**Comment by viviangb** [comment]
I would sooo love a PR please!

**Comment by kappys1** [comment]
What indicator is PR?

**Comment by viviangb** [comment]
@kappys1 sorry, a PR is a pull request. It's a way to add functionality to code.

**Comment by kappys1** [comment]
I do not know the acronyms yet haha

**Comment by theversal** [comment]
bfischer1121 it says me 
getStochRsi({ timePeriod=14, kPeriod=3, dPeriod=3 } = {}){
                                                         ^

SyntaxError: Unexpected token {

**Comment by theversal** [comment]
it says me 
TypeError: this.getRsi is not a function
what i am doing  wrong?

**Comment by anandanand84** [comment]
Stochrsi is now available

**Comment by veereshkumar-dev** [comment]
I'm a bit confused how to use next. 
shouldnt nextValue method only accept close?
thanks.

export declare class StochasticRsiInput extends IndicatorInput {
    values: number[];
    rsiPeriod: number;
    stochasticPeriod: number;
    kPeriod: number;
    dPeriod: number;
}

nextValue(input: StochasticRsiInput): StochasticRSIOutput
