### ISSUE TITLE
Feature Request : Candle Stick Pattern Hammer Identification 

### ISSUE THREAD

**Issue by sedhuait** [anandanand84/technicalindicators#75]
For Both Bullish and Bearish Hammer.

**Comment by JMoli** [comment]
Strong Bullish Hammer - Bullish Hammer - Strong Shooting Star - Shooting Star

![image](https://user-images.githubusercontent.com/5056967/38357138-c0f759a0-388f-11e8-8302-a8990b83f357.png)

**Comment by JMoli** [comment]
![image](https://user-images.githubusercontent.com/5056967/38357286-239011c4-3890-11e8-8af2-53bec562d14d.png)

**Comment by anandanand84** [comment]
This is added to the library thanks to @marcus-n3rd who added the complete set with full explanation in the PR. Feel free to check the PR and let us know if you have any comments
