### ISSUE TITLE
Bullish and Bearish

### ISSUE THREAD

**Issue by rahmansayed** [anandanand84/technicalindicators#76]
For Bullish and Bearish, they check against different indicators, some accept two candles, some accept three candles, if the user provided three candles to utilize all the indicators, for indicators that utilize two candles only they should use the last two candles not the first two

**Comment by anandanand84** [comment]
@rahmansayed I believe it always uses the last two candles for indicators which requires only two candles, can you provide an example where it didn't?

**Comment by rahmansayed** [comment]
for example in BullishHarami (a two candles only indicator), the code states
let firstdaysOpen   = data.open[0];
        let firstdaysClose  = data.close[0];
        let firstdaysHigh   = data.high[0];
        let firstdaysLow    = data.low[0]
        let seconddaysOpen  = data.open[1];
        let seconddaysClose = data.close[1];
        let seconddaysHigh  = data.high[1];
        let seconddaysLow   = data.low[1]
if the user provided three candles it should user indices 2 & 1 instead (or whatever ways data.X.length - 1 & data.X.length - 2)

**Comment by anandanand84** [comment]
@rahmansayed Can you check https://github.com/anandanand84/technicalindicators/issues/48 and see if that makes sense. You can take a look at the exact code which generates the required data at  https://github.com/anandanand84/technicalindicators/blob/master/src/candlestick/CandlestickFinder.ts#L54. If you still feel there is an issue, can you draw the candlestick using draw-candlestick finder as I have done in #48 and attach in the issue.

**Comment by rahmansayed** [comment]
Ok, fine, perfectly clear, thanks for the support
