### ISSUE TITLE
ADL division by zero

### ISSUE THREAD

**Issue by 3Ue** [anandanand84/technicalindicators#77]
In ADL.ts there is a possible division by zero if tick.high and tick.low are the same. That results in every result value afterwards being NaN.

https://github.com/anandanand84/technicalindicators/blob/02a270e56cad28ffa458ebf8c4d683a9161cb55b/src/volume/ADL.ts#L35

**Comment by anandanand84** [comment]
Fixed https://github.com/anandanand84/technicalindicators/blob/master/src/volume/ADL.ts#L36
