### ISSUE TITLE
Add support for small or big num

### ISSUE THREAD

**Issue by Dinfyru** [anandanand84/technicalindicators#80]
I have trouble with small numbers (js trouble).

Example (big.js https://github.com/MikeMcl/big.js/):
`Big(0.04421502399999999).minus(0.04421495);`

**Comment by anandanand84** [comment]
can you show me an example of your issue?

Also take a look at this https://github.com/anandanand84/technicalindicators/commit/e796d107280abab6aafd4a2af8609403c72c076f, you can set your own precision
```
eg: setConfig('precision' , 5)
```

**Comment by Dinfyru** [comment]
`toPrecision` only round number. This introduces discrepancies to the calculations. 
example
```
0.3 - 0.1                          // 0.19999999999999998
x = new Big(0.3)
x.minus(0.1)                       // "0.2"
x                                  // "0.3"
```

**Comment by anandanand84** [comment]
Technical indicators doesn't involve any calculation of money and using bignumber has significant performance issues which outweigh any benefits.

see https://github.com/anandanand84/technicalindicators/issues/53

**Comment by Dinfyru** [comment]
@anandanand84 you can do tests. Big js do it very fast.
https://github.com/MikeMcl/big.js/#performance

**Comment by Dinfyru** [comment]
```
Big div vs BigDecimal divide

 Method calls: 100000

 Random operands: 200000
 Maximum digits of operands: 50

 Decimal places: 20
 Rounding mode: 1

 Testing started . . . . . . . . . . done

 No mismatches.

 Time taken:

        BigDecimal  12952 ms
        Big         4182 ms
```
I do it on very low performance pc

**Comment by anandanand84** [comment]
@Dinfyru, I mean compared to the performance of native it will be significantly slower and it requires a major rewrite, On the next major rewrite I am planning to use web assembly or convert talib to work in webbrowser using webassembly. so doing conversion from big or bigdecimal doesnt make effective use of time.

I do use bigdecimal.js in https://traderslab.in for some calcualtion and it is pretty slow I am thinking of getting rid of it. BTW do not use the above mentioned website, it will be obsolete in few days

**Comment by Dinfyru** [comment]
Big.js was 3 times faster then bigdecimal.js

**Comment by anandanand84** [comment]
No plan to implement this. Closing. Thanks
