### ISSUE TITLE
Chart pattern

### ISSUE THREAD

**Issue by heekah7** [anandanand84/technicalindicators#81]
Any chance that we can add the like of Double bottom, Rising wedge, Double top, Head and shoulder, ... ?

**Comment by anandanand84** [comment]
This library is intended to work in browser, to add chart pattern recognition it requires deep learning, I did try out few implementations but did not workout, I do have a working model in tensorflow but that would not work in browser. I'll wait till https://github.com/PAIR-code/deeplearnjs/issues/33 is fixed so we can add it to the browser.

**Comment by heekah7** [comment]
Awesome! And you're awesome!

**Comment by heekah7** [comment]
Hi Ananda, I think that would be a solution to your issue.
https://medium.com/@muehler.v/node-js-meets-opencvs-deep-neural-networks-fun-with-tensorflow-and-caffe-ff8d52a0f072

**Comment by anandanand84** [comment]
@heekah7 Added preliminary pattern detection
