### ISSUE TITLE
Some indicators change based on # of values even above `period`

### ISSUE THREAD

**Issue by flesler** [anandanand84/technicalindicators#83]
For example:, calling RSI with `period 14`. These are the outputs based on the inputs:
```
[ 0.08581, 0.08486146, 0.085, 0.08350007, 0.0839, 0.085, 0.08486001, 0.084873, 0.08573899, 0.0866, 0.08919999, 0.08690268, 0.08749999, 0.08689999, 0.0889, 0.08650001, 0.08523572, 0.0852799631
--> [ 0, 60.99, 51.52, 47.35, 47.51 ]
```
```
[ 0.08454304, 0.08581, 0.08486146, 0.085, 0.08350007, 0.0839, 0.085, 0.08486001, 0.084873, 0.08573899, 0.0866, 0.08919999, 0.08690268, 0.08749999, 0.08689999, 0.0889, 0.08650001, 0.08523572, 0.0852799631
--> [ 0, 58.84, 64.57, 54.73, 50.37, 50.52 ]
```

As you can see, the 2nd call has one more value at the beginning. As I understand it, in both cases the input has enough values to satisfy the period (`14`). Is RSI special in that it's relative or sth and it changes based on more values than `period`? If so, How can you ensure it matches consistently with things like TradingView, how many more values do I need to provide?

Same thing happens with PSAR.

**Comment by anandanand84** [comment]
I did look at trading view vs this library (http://cryptotrading-hub), both seems to be match exact, see the attached image from both.


I havent looked at the logic for the RSI but it may be similar to this issue. https://github.com/anandanand84/technicalindicators/issues/43

<img width="1469" alt="screen shot 2017-12-16 at 6 56 20 pm" src="https://user-images.githubusercontent.com/5538452/34075682-3f5967aa-e293-11e7-900b-da1397f500d3.png">
<img width="1331" alt="screen shot 2017-12-16 at 6 56 09 pm" src="https://user-images.githubusercontent.com/5538452/34075685-4b3e2aec-e293-11e7-9d81-8010d91ca573.png">

**Comment by flesler** [comment]
For the MACD I am keeping at least slowPeriod+FastPeriod so it's not the same issue as that other one

**Comment by flesler** [comment]
http://cryptotrading-hub.com uses this library for its indicators?

**Comment by anandanand84** [comment]
@flesler yes

**Comment by anandanand84** [comment]
![image](https://user-images.githubusercontent.com/5538452/37355265-563f335c-26b1-11e8-9fe2-1064740df8ce.png)

This is working as expected, as for your RSI, the calculation depends on Average Gain and Average Loss which depends on previous gains and it is not calculated based on last period values, but from pervious gains ( see attached image)

**Comment by flesler** [comment]
@anandanand84 can you explain? you mean that if the period is 14 and I give 14 (or 15?) data points it should work correctly? If so, that's not the case

**Comment by anandanand84** [comment]
@flesler Think about the calculation of average gain based on the above formula.

if you have 1,4,5,6,9 values and you want to calculate avg gain for period 2. then 

Based on above formula

Gains for above series is   3, 1, 1, 3
First average gain = 3 / 2 = 1.5
Second average gain = ((1.5 * 1) + 1) /  2 = 1.1  

The second average gain is not equal to 1 / 2  = 0.5 which is calculated from the last two values which is what you are expecting.

Average gain is base for RSI so it will also follow the same rule and its values is not based on the period values and will be affected by values prior to period size.

Hope it makes sense.
