### ISSUE TITLE
Add MFI indicator

### ISSUE THREAD

**Issue by rclai** [anandanand84/technicalindicators#84]
This is an awesome library. Are you able to add the MFI indicator?
https://www.investopedia.com/ask/answers/121214/what-are-main-differences-and-similarities-between-money-flow-index-mfi-relative-strength-index-rsi.asp

**Comment by anandanand84** [comment]
@rclai sure I'll add it

**Comment by anandanand84** [comment]
Added in 1.1.5

**Comment by rclai** [comment]
🎊
