### ISSUE TITLE
node_modules/technicalindicators/declarations/oscillators/CCI.d.ts(1,28): Cannot find module '../../src/StockData'

### ISSUE THREAD

**Issue by davidstoneham** [anandanand84/technicalindicators#93]
looks like the StockData is in the same declarations folder and not back in src

**Comment by anandanand84** [comment]
@davidstoneham  what version of typescript are you using?

**Comment by redstrike** [comment]
@anandanand84 I have the same problem after updated to **technicalindicators v1.1.1** & **TypeScript v2.7.1**

After checking the lib directory, I see **no /src/ folder in /declarations/**. Also, the correct import path for [this line of code](https://github.com/anandanand84/technicalindicators/blob/4cac000adc435c07c19ac69bda0e3c7c71c25c01/declarations/oscillators/CCI.d.ts#L1) is:
```js
import { CandleData } from '../StockData';
```

**Comment by anandanand84** [comment]
Fixed in 1.1.3
