### ISSUE TITLE
Unexpected identifier async _initialize()

### ISSUE THREAD

**Issue by napindc** [anandanand84/technicalindicators#94]
I'm getting the below error when using 1.1.1 of this package. Is there anyway to fix this?

```
Detailed stack trace: /user_code/node_modules/technicalindicators/node_modules/keras-js/lib/Model.js:107
  async _initialize() {
        ^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/technicalindicators/node_modules/keras-js/lib/index.js:22:37)
```

**Comment by anandanand84** [comment]
@napindc what version of nodejs are you using?

**Comment by napindc** [comment]
I'm using 8.9.3

**Comment by anandanand84** [comment]
@napindc I tried with 8.9.3 it works fine, can you check again the verison of technical indicators and nodejs, below is the list of commands I used, Is there a different way to reproduce.

![image](https://user-images.githubusercontent.com/5538452/35473129-0dddfb2c-0341-11e8-98ee-c2d4148aa327.png)

**Comment by anandanand84** [comment]
Its most likely a nodejs version issue, just check the firebase environment.

**Comment by fredmarques** [comment]
Firebase uses 6.11.5.
I'm using node 9.4 and works perfectly, but on Firebase I got the same issue.

**Comment by anandanand84** [comment]
@napindc @fredmarques ok can you check if following node < 6.4 in readme helps, basically it uses transpiled es6 version.

```
npm install --save babel-polyfill
npm install --save technicalindicators
```

```
require('babel-polyfill');
const SMA = require('technicalindicators/dist/browser').SMA;
```

**Comment by fredmarques** [comment]
@anandanand84  I read that on README before but didn't helped. The problem seems to be Keras-js dependecy as you can read on the error stack trace:

> Detailed stack trace: /user_code/node_modules/technicalindicators/node_modules/keras-js/lib/Model.js:107


As a workaround I did a `npm install --save-exact technicalindicators@1.0.19` to use v1.0.19 which dosen't have Keras-js as dependency and the error is gone.

**Comment by napindc** [comment]
Genius... I just downgraded and it works for me as well. Thanks!

**Comment by anandanand84** [comment]
Upstream issue for node < 6.4 https://github.com/transcranial/keras-js/issues/103
