### ISSUE TITLE
'period' value in typing definition seems redundant for MACDInput

### ISSUE THREAD

**Issue by windware** [anandanand84/technicalindicators#96]
I'm using MACD.calculate method and when I supply these values,
- values
- fastPeriod
- slowPeriod
- signalPeriod
- SimpleMAOscillator
- SimpleMASignal

TypeScript complains that I'm missing 'period' which is in fact not used in the calculation but is being mandated in the typing definition.

Currently, I just pass 'period' as null to avoid the error.

**Comment by anandanand84** [comment]
Thanks for reporting. I will fix that in the next release.

**Comment by anandanand84** [comment]
Fixed in 1.1.3
